name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install mocha
      run: npm install -g mocha

    # Install dependencies including Mocha and Chai
    - run: npm ci

    # Build the project if applicable
    - run: npm run build --if-present
    
    # Run tests (Mocha with Chai)
    - name: Run tests
      run: mocha tests/add.test.js
    
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.4
            
